### ISSUE TITLE
Uncaught TypeError: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by kenorb** [dzaima/ArtAttack#1]
When running Tournament with few bots, it errors.

> Uncaught TypeError: Cannot read property 'classList' of null
    at HTMLTableRowElement.onmouseover (VM12596 artattack.htm:4)

Lines:
```
[...document.querySelectorAll(".pointed")].forEach(c=>c.classList.remove("pointed"));
mark.classList.add("pointed");
```

![image](https://user-images.githubusercontent.com/266306/44620611-4d91f180-a88f-11e8-95f9-a09cc48e6a19.png)

**Comment by dzaima** [comment]
I know this happens, I'm just too lazy to do anything about it. It happens because when you hover an entry in the table it wants to highlight the entry in the map but there is no board so it errors

**Comment by dzaima** [comment]
fixed
